leagueID = 325879
season = 2018

bye_weeks = {
  'Ari': 9,
  'Atl': 8,
  'Bal':10,
  'Buf':11,
  'Car': 4,
  'Chi': 5,
  'Cin': 9,
  'Cle':11,
  'Dal': 8,
  'Den':10,
  'Det': 6,
  'GB' : 7,
  'Hou':10,
  'Ind': 9,
  'Jax': 9,
  'KC' :12,
  'LAC': 8,
  'LAR':12,
  'Mia':11,
  'Min':10,
  'NE' :11,
  'NO' : 6,
  'NYG': 9,
  'NYJ':11,
  'Oak': 7,
  'Phi': 9,
  'Pit': 7,
  'SF' :11,
  'Sea': 7,
  'TB' : 5,
  'Ten': 8,
  'Wsh': 4,
}

aliases = {
  'Odell Beckham Jr.': 'Odell Beckham',
  'DJ Moore': 'D.J. Moore',
  'Marvin Jones Jr.': 'Marvin Jones',
  'Will Fuller V': 'Will Fuller',
  'Mark Ingram II': 'Mark Ingram',
  'Packers D/ST': 'Green Bay D/ST',
  'Rams D/ST':  'Los Angeles Rams D/ST',
  'Texans D/ST': 'Houston D/ST',
  'Bears D/ST': 'Chicago D/ST',
  'Cardinals D/ST': 'Arizona D/ST',
  'Browns D/ST': 'Cleveland D/ST',
  'Chargers D/ST': 'Los Angeles Chargers D/ST',
  'Seahawks D/ST': 'Seattle D/ST',
  'Eagles D/ST': 'Philadelphia D/ST',
  'Vikings D/ST': 'Minnesota D/ST',
  'Jaguars D/ST': 'Jacksonville D/ST',
  'Jets D/ST': 'New York Jets D/ST',
  'Titans D/ST':  'Tennessee D/ST',
  'Dolphins D/ST': 'Miami D/ST',
  'Redskins D/ST': 'Washington D/ST',
  'Cowboys D/ST': 'Dallas D/ST',
  'Lions D/ST': 'Detroit D/ST',
  'Ravens D/ST': 'Baltimore D/ST',
  'Steelers D/ST': 'Pittsburgh D/ST',
  'Colts D/ST': 'Indianapolis D/ST',
  'Broncos D/ST': 'Denver D/ST',
  'Panthers D/ST': 'Carolina D/ST',
  'Bengals D/ST': 'Cincinnati D/ST',
  'Bills D/ST':  'Buffalo',
  'Giants D/ST': 'New York Giants D/ST',
  'Buccaneers D/ST': 'Tampa Bay D/ST',
  'Patriots D/ST': 'New England D/ST',
  '49ers D/ST': 'San Francisco D/ST',
  'Falcons D/ST': 'Atlanta D/ST',
  'Raiders D/ST': 'Oakland D/ST',
  'Chiefs D/ST': 'Kansas City D/ST',
  'Saints D/ST': 'New Orleans D/ST',
}

abbrevs = {
  'Cardinals': 'Ari',
  'Falcons': 'Atl',
  'Ravens': 'Bal',
  'Bills': 'Buf',
  'Panthers': 'Car',
  'Bears': 'Chi',
  'Bengals': 'Cin',
  'Browns': 'Cle',
  'Cowboys': 'Dal',
  'Broncos': 'Den',
  'Lions': 'Det',
  'Packers': 'GB',
  'Texans': 'Hou',
  'Colts': 'Ind',
  'Jaguars': 'Jax',
  'Chiefs': 'KC',
  'Chargers': 'LAC',
  'Rams': 'LAR',
  'Dolphins': 'Mia',
  'Vikings': 'Min',
  'Patriots': 'NE',
  'Saints': 'NO',
  'Giants': 'NYG',
  'Jets': 'NYJ',
  'Raiders': 'Oak',
  'Eagles': 'Phi',
  'Steelers': 'Pit',
  '49ers': 'SF',
  'Seahawks': 'Sea',
  'Buccaneers': 'TB',
  'Titans': 'Ten',
  'Redskins': 'Wsh',
}